BAU - Dropwizard 2.0.0 upgrade - fixes
- Dropwizard 2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
  Add parent `dropwizard-dependencies` which has versions of transitive dependencies specified and can be overridden.

  We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.2` but dropwizard uses `2.10.1`

- Upgraded dropwizard-sentry library too without which builds are failing with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()'`

- Added library `org.glassfish.jersey.bundles.repackaged` as it is not added anymore by dropwizard v2.x.x